#ifndef TENSORFLOW_ADDON_ANNC_FUSED_OP_H_
#define TENSORFLOW_ADDON_ANNC_FUSED_OP_H_

#include <dlfcn.h>

#include <string>
#include <unordered_map>
#include <vector>

#include "Kernel/ExecutionContext.h"
#include "tensorflow/core/framework/op.h"
#include "tensorflow/core/framework/op_kernel.h"
#include "tensorflow/core/lib/core/status.h"
#include "tensorflow/core/platform/mutex.h"

#include "annc_jit_cache.h"

namespace annc {
namespace threadpool {
class AnncThreadPool;
}  // namespace threadpool
}  // namespace annc

namespace tensorflow {

struct AnncFusedProfileSample;

// ANNCFused Op - Carries fused kernels generated by ANNC
// NOTE: Op registration (REGISTER_OP / REGISTER_KERNEL_BUILDER) is in
// annc_fused_op_register.cc to avoid duplicate registration when multiple
// source files include this header.

// ANNCFused kernel implementation.
class ANNCFusedOp : public OpKernel {
 public:
  explicit ANNCFusedOp(OpKernelConstruction* context);
  ~ANNCFusedOp() override;

  void Compute(OpKernelContext* context) override;

 private:
  // Load the shared library produced by ANNCOptimizerPass.
  Status LoadLibrary(const std::string& so_path);
  Status ResolveLibrarySymbols(const std::string& so_path);

  annc::jit::JitCompileResult CompileJitKernel(
      const std::vector<annc::jit::JitArgumentSignature>& arguments);

  Status ExecuteMlirCifaceKernel(OpKernelContext* context,
                                 void* kernel_function,
                                 bool profile_enabled,
                                 AnncFusedProfileSample* profile_sample);
  Status ExecuteExecutionV2Kernel(OpKernelContext* context,
                                  void* kernel_function,
                                  bool profile_enabled,
                                  AnncFusedProfileSample* profile_sample);

  // Input classification counts derived from FusionInfo::args during rewrite.
  int num_constants_;
  int num_fixed_;
  int num_dynamic_;

  // Core runtime attributes copied from or derived from fusion metadata.
  std::string kernel_name_;
  // Name-independent identity of the fusion function used by the JIT cache.
  std::string template_fingerprint_;
  int num_outputs_;
  // One entry per output; used to build ranked output memref descriptors.
  std::vector<int> output_ranks_;
  // Output-axis indices whose sizes come from the first dynamic input.
  std::vector<int> dynamic_dims_;
  // One entry per input in constants/fixed/dynamic TensorFlow input order.
  std::vector<int> input_ranks_;
  // Comma-separated dimensions per output; "?" denotes a dynamic dimension.
  std::vector<std::string> output_shapes_;
  // output_shapes_ parsed once in the constructor (-1 for dynamic dimensions);
  // the hot path uses this to avoid re-parsing the attribute strings per call.
  std::vector<std::vector<int64_t>> output_shape_specs_;
  // Permutation over [input memrefs..., output memrefs...] for the kernel call.
  std::vector<int> kernel_arg_order_;
  // Compatibility placeholder; currently read but not interpreted by runtime.
  std::string symbolic_signature_str_;
  // Semantic label used for runtime policy such as output initialization.
  std::string fusion_pattern_;
  // Legacy homogeneous output dtype retained by the TensorFlow Op contract.
  DataType dtype_;
  std::vector<DataType> output_types_;
  // Generated library containing _mlir_ciface_<kernel_name_>.
  std::string shared_lib_path_;
  // Fusion-only ATIR module consumed by runtime JIT compilation.
  std::string atir_module_path_;
  // Calling convention: legacy "mlir_ciface" or context-based
  // "annc_execution_v2".
  std::string abi_;
  // Whether runtime clears output tensors before calling the generated kernel.
  bool zero_initialize_outputs_;

  // Runtime state
  // Shared-library path associated with the currently resolved kernel symbol.
  std::string current_so_path_;
  // dlopen handle owned by the process-wide library cache.
  void* handle_;
  // Resolved _mlir_ciface_<kernel_name_> entry point.
  void* mlir_ciface_func_;
  // Optional hooks that expose TensorFlow's thread pool to generated kernels.
  void (*annc_set_current_threadpool_)(annc::threadpool::AnncThreadPool*);
  annc::threadpool::AnncThreadPool* (*annc_get_current_threadpool_)();
  // True after the current shared library and kernel symbol are resolved.
  bool loaded_;

  // Process-wide cache prevents repeated dlopen calls for the same library.
  static mutex lib_cache_mu_;
  static std::unordered_map<std::string, void*> lib_cache_;
};

}  // namespace tensorflow

#endif  // TENSORFLOW_ADDON_ANNC_FUSED_OP_H_
