#ifndef TENSORFLOW_ADDON_ANNC_FUSED_OP_H_
#define TENSORFLOW_ADDON_ANNC_FUSED_OP_H_

#include "tensorflow/core/framework/op.h"
#include "tensorflow/core/framework/op_kernel.h"
#include "tensorflow/core/lib/core/status.h"
#include "tensorflow/core/platform/mutex.h"

#include <dlfcn.h>
#include <string>
#include <unordered_map>
#include <vector>

namespace annc {
namespace threadpool {
class AnncThreadPool;
}  // namespace threadpool
}  // namespace annc

namespace tensorflow {

// ANNCFused Op - Carries fused kernels generated by ANNC
// NOTE: Op registration (REGISTER_OP / REGISTER_KERNEL_BUILDER) is in
// annc_fused_op_register.cc to avoid duplicate registration when multiple
// source files include this header.

// ANNCFused kernel implementation.
class ANNCFusedOp : public OpKernel {
 public:
  explicit ANNCFusedOp(OpKernelConstruction* context);
  ~ANNCFusedOp() override;

  void Compute(OpKernelContext* context) override;

 private:
  // Load the shared library produced by ANNCOptimizerPass.
  Status LoadLibrary(const std::string& so_path);

  Status ExecuteMlirCifaceKernel(OpKernelContext* context);

  // Input classification counts
  int num_constants_;
  int num_fixed_;
  int num_dynamic_;

  // Core attributes
  std::string kernel_name_;
  int num_outputs_;
  std::vector<int> output_ranks_;
  std::vector<int> dynamic_dims_;
  std::vector<int> input_ranks_;
  std::vector<std::string> output_shapes_;
  std::vector<int> kernel_arg_order_;
  std::string symbolic_signature_str_;
  DataType dtype_;
  std::string shared_lib_path_;
  std::string abi_;

  // Runtime state
  std::string current_so_path_;
  void* handle_;
  void* mlir_ciface_func_;
  void (*annc_set_current_threadpool_)(annc::threadpool::AnncThreadPool*);
  annc::threadpool::AnncThreadPool* (*annc_get_current_threadpool_)();
  bool loaded_;

  // Static library handle cache (memory cache for loaded libs)
  static mutex lib_cache_mu_;
  static std::unordered_map<std::string, void*> lib_cache_;
};

}  // namespace tensorflow

#endif  // TENSORFLOW_ADDON_ANNC_FUSED_OP_H_
