package(
    default_visibility = [
        "//visibility:public",
    ],
    licenses = ["notice"],
)

cc_library(
    name = "hlo_util",
    hdrs = ["hlo_util.h"]
)

cc_library(
    name = "kdnn_util",
    hdrs = ["kdnn_util.h"]
)

cc_library(
    name = "optimizer_util",
    hdrs = ["optimizer_util.h"]
)

cc_library(
    name = "blas_util",
    hdrs = ["blas_util.h"]
)
